// @ts-check
import { defineSiteConfig } from './src/config.mjs'

export const siteConfig = defineSiteConfig({
  // Required site identity. Start here, then adjust the locale fields below.
  origin: 'https://example.com',
  logo: '/img/logo.svg',
  appearance: true,
  copyrightYear: new Date().getFullYear(),
  namespace: 'ermaozi',
  mediaOrigin: '',
  replaceAssets: false,
  autoFrontmatter: true,
  twitterHandle: '',
  social: [
    { icon: 'github', link: 'https://github.com/ermaozi/astro-theme-ermaozi' },
  ],
  navbarSocialInclude: ['github', 'twitter', 'discord', 'facebook'],
  footer: {
    message: 'Powered by <a target="_blank" rel="noopener" href="https://astro.build/">Astro</a> &amp; <a target="_blank" rel="noopener" href="https://github.com/ermaozi/astro-theme-ermaozi">ermaozi</a>',
    copyright: `Copyright © ${new Date().getFullYear()} ermaozi`,
  },
  profile: {
    avatar: '/img/logo.svg',
    circle: true,
    location: 'Internet',
    organization: 'Open source community',
    layout: 'right',
  },
  tagsTheme: 'colored',
  meta: {
    tags: true,
    readingTime: true,
    wordCount: true,
    createTime: 'short',
  },
  readingTime: { wordPerMinute: 300 },
  lastUpdated: { formatOptions: { dateStyle: 'short', timeStyle: 'short' } },
  contributors: true,
  changelog: false,
  postCover: 'right',
  pagination: { perPage: 15 },
  categoriesExpand: 'deep',
  transition: {
    appearance: 'fade',
    page: true,
    postList: true,
  },
  search: {
    provider: 'local',
    // Algolia: provider, appId, apiKey, indexName or indices, locales and keyboardShortcuts.
  },
  codeHighlighter: { twoslash: true, lineNumbers: 10, renderIndentGuides: true, colorizedBrackets: true },
  plugins: { markdownPower: { imageSize: false } },
  copyCode: true,
  pageContextMenu: { chatgpt: true, claude: true, perplexity: true },
  // Add or remove complete locale blocks to control the language switcher.
  locales: {
    'zh-CN': {
      siteName: 'ermaozi',
      blogName: '示例博客',
      docsName: '文档中心',
      description: '一个支持双语内容、全文搜索、深色模式和增强 Markdown 的 Astro 静态博客主题。',
      authorName: '站点作者',
      authorDescription: '使用 ermaozi 发布文章、文档和项目记录。',
      profileTagline: '记录、整理与分享',
      keywords: 'Astro,静态博客,Markdown,双语网站,主题',
      home: '/',
      homeText: '首页',
      postsText: '博客',
      copyPageText: '复制页面',
      copiedPageText: '复制成功',
      copingPageText: '复制中..',
      copyTagline: '将页面以 Markdown 格式复制供 LLMs 使用',
      viewMarkdown: '以 Markdown 格式查看',
      viewMarkdownTagline: '以纯文本查看此页面',
      askAIText: '在 {name} 中打开',
      askAITagline: '向 {name} 提问有关此页面',
      askAIMessage: '阅读 {link} 并回答内容相关的问题。',
      collections: [
        { type: 'post', dir: 'blog', title: '博客' },
        {
          type: 'doc',
          dir: 'docs',
          title: '文档中心',
          sidebar: [
            {
              text: '指南',
              prefix: 'guide',
              icon: 'icon-park-outline:guide-board',
              collapsed: false,
              items: [
                { text: '基础', icon: 'construction', collapsed: false, items: ['getting-started', 'configuration', { text: '公共 API 与样式定制', link: 'api', badge: { text: 'New', type: 'warning' } }] },
                { text: '内容能力', link: 'content', icon: 'simple-icons:astro' },
              ],
            },
            { text: '参考', link: '---', icon: 'more-circle' },
            { text: 'Astro', link: 'https://astro.build/', icon: 'simple-icons:astro' },
          ],
        },
      ],
      navigation: [
        { label: '<span>博客</span>', href: '/blog/', icon: 'home', activeMatch: '^/(blog|article)/' },
        {
          label: '文档',
          icon: 'material-symbols:docs-outline',
          activeMatch: '^/docs/',
          items: [
            '/docs/',
            {
              text: '指南',
              icon: 'icon-park-outline:guide-board',
              prefix: '/docs/guide/',
              items: [
                { text: '快速开始', link: 'getting-started/', icon: 'rocket' },
                { text: '站点配置', link: 'configuration/', icon: 'construction' },
                { text: '内容能力', link: 'content/', icon: 'simple-icons:astro', badge: { text: 'New', type: 'warning' } },
                { text: 'Astro', link: 'https://astro.build/', icon: 'simple-icons:astro' },
              ],
            },
          ],
        },
        {
          label: '更多',
          icon: 'more-circle',
          items: [
            { label: '分类', href: '/blog/categories/', icon: '/img/logo.svg' },
            { label: '标签', href: '/blog/tags/', icon: { svg: '<svg viewBox="0 0 24 24"><path fill="currentColor" d="M3 4h8l10 10-7 7L4 11V4Zm4 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4Z"/></svg>' } },
            { label: '归档', href: '/blog/archives/', icon: 'archive' },
            { label: '关于', href: '/about/', icon: 'verified' },
          ],
        },
      ],
    },
    'en-US': {
      siteName: 'ermaozi',
      blogName: 'Example Blog',
      docsName: 'Documentation',
      description: 'An Astro static blog theme with bilingual content, full-text search, dark mode, and enhanced Markdown.',
      authorName: 'Site Author',
      authorDescription: 'Publish articles, documentation, and project notes with ermaozi.',
      profileTagline: 'Write, organize, and share',
      keywords: 'Astro,static blog,Markdown,bilingual site,theme',
      home: '/en/',
      homeText: 'Home',
      postsText: 'Blog',
      copyPageText: 'Copy page',
      copiedPageText: 'Copied !',
      copingPageText: 'Copying..',
      copyTagline: 'Copy page as Markdown for LLMs',
      viewMarkdown: 'View as Markdown',
      viewMarkdownTagline: 'View this page as plain text',
      askAIText: 'Open in {name}',
      askAITagline: 'Ask {name} about this page',
      askAIMessage: 'Read {link} and answer content-related questions.',
      collections: [
        { type: 'post', dir: 'blog', title: 'Blog' },
        {
          type: 'doc',
          dir: 'docs',
          title: 'Documentation',
          sidebar: [
            {
              text: 'Guides',
              prefix: 'guide',
              icon: 'icon-park-outline:guide-board',
              collapsed: false,
              items: [
                { text: 'Basics', icon: 'construction', collapsed: false, items: ['getting-started', 'configuration', { text: 'Public API and styling', link: 'api', badge: { text: 'New', type: 'warning' } }] },
                { text: 'Content features', link: 'content', icon: 'simple-icons:astro' },
              ],
            },
            { text: 'Reference', link: '---', icon: 'more-circle' },
            { text: 'Astro', link: 'https://astro.build/', icon: 'simple-icons:astro' },
          ],
        },
      ],
      navigation: [
        { label: '<span>Blog</span>', href: '/en/blog/', icon: 'home', activeMatch: '^/en/(blog|article)/' },
        {
          label: 'Docs',
          icon: 'material-symbols:docs-outline',
          activeMatch: '^/en/docs/',
          items: [
            '/en/docs/',
            {
              text: 'Guides',
              icon: 'icon-park-outline:guide-board',
              prefix: '/en/docs/guide/',
              items: [
                { text: 'Quick start', link: 'getting-started/', icon: 'rocket' },
                { text: 'Site configuration', link: 'configuration/', icon: 'construction' },
                { text: 'Content features', link: 'content/', icon: 'simple-icons:astro', badge: { text: 'New', type: 'warning' } },
                { text: 'Astro', link: 'https://astro.build/', icon: 'simple-icons:astro' },
              ],
            },
          ],
        },
        {
          label: 'More',
          icon: 'more-circle',
          items: [
            { label: 'Categories', href: '/en/blog/categories/', icon: '/img/logo.svg' },
            { label: 'Tags', href: '/en/blog/tags/', icon: { svg: '<svg viewBox="0 0 24 24"><path fill="currentColor" d="M3 4h8l10 10-7 7L4 11V4Zm4 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4Z"/></svg>' } },
            { label: 'Archives', href: '/en/blog/archives/', icon: 'archive' },
            { label: 'About', href: '/en/about/', icon: 'verified' },
          ],
        },
      ],
    },
  },
  // Optional services stay off until their provider credentials are configured.
  features: {
    engagement: false,
    popularPosts: false,
    comments: false,
  },
  repository: {
    url: '',
    branch: 'main',
    contentDir: 'content',
    editLinkPattern: '',
  },
  copyright: {
    enabled: true,
    author: 'Site Author',
    creation: 'original',
    license: 'CC-BY-4.0',
  },
  encrypt: {
    global: false,
    // Demo only: replace or remove these passwords before protecting real content.
    admin: 'plume-admin',
    rules: {
      '/blog/encrypted-example/': 'rule-demo',
    },
  },
  // Advanced content features. Keep the defaults until a documented need appears.
  markdown: {
    mark: 'lazy',
    math: { type: 'katex', delimiters: 'dollars', copy: true, mhchem: false },
    icon: {
      provider: 'iconify',
      // prefix: 'mdi',
      // IconFont/Font Awesome providers can load one or more .css/.js asset URLs.
      // assets: [],
    },
    repl: { go: true, kotlin: true, rust: true, python: true },
    table: true,
    obsidian: { wikiLink: true, embedLink: true, callout: true, comment: true },
    abbr: true,
    annotation: true,
    plot: true,
    qrcode: true,
    caniuse: true,
    include: true,
    chartjs: true,
    echarts: true,
    flowchart: true,
    markmap: true,
    plantuml: true,
    mermaid: true,
    acfun: true,
    bilibili: true,
    youtube: true,
    pdf: true,
    audioReader: true,
    artPlayer: true,
    npmTo: ['pnpm', 'yarn', 'npm'],
    env: {
      references: { astro: { href: 'https://astro.build/', title: 'Astro' } },
      abbreviations: { SSG: 'Static Site Generator' },
      annotations: { preset: 'This annotation is configured once in `site.config.mjs`.' },
    },
    encryptPassword: '',
    fileTree: { icon: 'colored' },
    DANGEROUS_ALLOW_SCRIPT_EXECUTION: false,
    DANGEROUS_SCRIPT_EXECUTION_ALLOWLIST: [],
  },
  watermark: {
    enabled: false,
    fullPage: true,
    options: {
      content: 'ermaozi',
      width: 240,
      height: 180,
      rotate: -22,
      globalAlpha: 0.12,
    },
  },
  bulletin: {
    enabled: true,
    layout: 'top-right',
    border: true,
    lifetime: 'session',
    enablePage: ({ path }) => path === '/landing/',
    title: 'Welcome',
    contentType: 'markdown',
    content: 'Configure or disable this bulletin in `site.config.mjs`.',
    contentFile: '',
  },
  services: {
    statsBase: '',
    statsVisitorHeader: 'X-Site-Visitor',
  },
  comment: {
    provider: 'Giscus',
    comment: true,
    repo: '',
    repoId: '',
    category: '',
    categoryId: '',
  },
  verification: {
    yandex: '',
    baidu: '',
  },
})
