import { defineCollection } from 'astro:content'
import { glob } from 'astro/loaders'
import { z } from 'astro/zod'

const friendItemSchema = z.looseObject({
  name: z.string(),
  link: z.string(),
  avatar: z.string().optional(),
  desc: z.string().optional(),
  location: z.string().optional(),
  organization: z.string().optional(),
  socials: z.array(z.looseObject({ icon: z.union([z.string(), z.object({ svg: z.string(), name: z.string().optional() })]), link: z.string(), ariaLabel: z.string().optional() })).optional(),
  backgroundColor: z.union([z.string(), z.object({ light: z.string(), dark: z.string() })]).optional(),
  color: z.union([z.string(), z.object({ light: z.string(), dark: z.string() })]).optional(),
  nameColor: z.union([z.string(), z.object({ light: z.string(), dark: z.string() })]).optional(),
})

const content = defineCollection({
  loader: glob({
    base: new URL('../content/', import.meta.url),
    pattern: ['**/*.md', '!**/*.snippet.md'],
    generateId: ({ entry }) => entry.replace(/\.md$/, ''),
  }),
  schema: z.looseObject({
    title: z.string(),
    description: z.string().optional().default(''),
    permalink: z.string().optional(),
    createTime: z.union([z.string(), z.date(), z.literal(false)]).optional(),
    updateTime: z.union([z.string(), z.date()]).optional(),
    date: z.union([z.string(), z.date()]).optional(),
    time: z.union([z.string(), z.date()]).optional(),
    lang: z.string().optional(),
    translationOf: z.string().optional(),
    type: z.enum(['post', 'doc', 'page']).optional(),
    order: z.number().optional(),
    group: z.string().optional(),
    badge: z.union([z.string(), z.looseObject({
      text: z.string().optional(),
      type: z.string().optional(),
      color: z.string().optional(),
      bgColor: z.string().optional(),
      borderColor: z.string().optional(),
    })]).optional(),
    icon: z.union([z.string(), z.object({ svg: z.string(), name: z.string().optional() })]).optional(),
    tags: z.array(z.string()).optional().default([]),
    tag: z.union([z.string(), z.array(z.string())]).optional(),
    author: z.union([
      z.string(),
      z.looseObject({ name: z.string(), url: z.string().optional(), email: z.string().optional() }),
      z.array(z.union([z.string(), z.looseObject({ name: z.string(), url: z.string().optional(), email: z.string().optional() })])),
    ]).optional(),
    head: z.array(z.unknown()).optional(),
    home: z.boolean().optional(),
    signDown: z.boolean().optional(),
    config: z.array(z.looseObject({ type: z.string() })).optional(),
    bannerMask: z.union([z.number(), z.looseObject({ light: z.number().optional(), dark: z.number().optional() })]).optional(),
    hero: z.looseObject({ name: z.string().optional(), tagline: z.string().optional(), text: z.string().optional(), actions: z.array(z.looseObject({})).optional() }).optional(),
    pageClass: z.string().optional(),
    sidebar: z.union([z.boolean(), z.string()]).optional(),
    aside: z.union([z.boolean(), z.literal('left')]).optional(),
    outline: z.union([z.literal(false), z.number(), z.tuple([z.number(), z.number()]), z.literal('deep')]).optional(),
    navbar: z.boolean().optional(),
    externalLinkIcon: z.boolean().optional(),
    externalLink: z.boolean().optional(),
    backToTop: z.boolean().optional(),
    footer: z.boolean().optional(),
    llmstxt: z.boolean().optional(),
    bulletin: z.boolean().optional(),
    comments: z.boolean().optional(),
    pageview: z.boolean().optional(),
    editLink: z.union([z.boolean(), z.string()]).optional(),
    editLinkPattern: z.string().optional(),
    lastUpdated: z.boolean().optional(),
    prev: z.union([z.literal(false), z.string(), z.looseObject({
      link: z.string(),
      text: z.string().optional(),
      icon: z.union([z.string(), z.object({ svg: z.string() })]).optional(),
    })]).optional(),
    next: z.union([z.literal(false), z.string(), z.looseObject({
      link: z.string(),
      text: z.string().optional(),
      icon: z.union([z.string(), z.object({ svg: z.string() })]).optional(),
    })]).optional(),
    changelog: z.boolean().optional(),
    gitInclude: z.array(z.string()).optional(),
    readingTime: z.boolean().optional(),
    contributors: z.union([
      z.boolean(),
      z.array(z.union([z.string(), z.object({ name: z.string(), url: z.string().optional() })])),
    ]).optional(),
    copyright: z.union([
      z.boolean(),
      z.string(),
      z.object({
        author: z.union([z.string(), z.object({ name: z.string(), url: z.string().optional() })]).optional(),
        creation: z.enum(['original', 'translate', 'reprint']).optional(),
        source: z.string().optional(),
        license: z.union([z.string(), z.object({ name: z.string(), url: z.string().optional() })]).optional(),
      }),
    ]).optional(),
    search: z.boolean().optional(),
    seo: z.boolean().optional(),
    sitemap: z.union([z.boolean(), z.looseObject({
      changefreq: z.enum(['always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never']).optional(),
      priority: z.number().min(0).max(1).optional(),
      img: z.array(z.looseObject({ url: z.string() })).optional(),
      video: z.array(z.looseObject({ thumbnail_loc: z.string(), title: z.string(), description: z.string() })).optional(),
      news: z.array(z.looseObject({})).optional(),
    })]).optional(),
    layout: z.string().optional(),
    pageLayout: z.union([z.string(), z.literal(false)]).optional(),
    collection: z.string().optional(),
    stats: z.boolean().optional(),
    article: z.boolean().optional(),
    draft: z.boolean().optional(),
    excerpt: z.union([z.boolean(), z.string()]).optional(),
    password: z.union([z.string(), z.number(), z.array(z.union([z.string(), z.number()]))]).optional(),
    passwordHint: z.string().optional(),
    watermark: z.union([
      z.boolean(),
      z.looseObject({
        content: z.union([z.string(), z.array(z.string())]).optional(),
        contentType: z.enum(['text', 'image', 'multi-line-text', 'rich-text']).optional(),
        image: z.string().optional(),
        width: z.number().optional(),
        height: z.number().optional(),
        imageWidth: z.number().optional(),
        imageHeight: z.number().optional(),
        fontColor: z.string().optional(),
        globalAlpha: z.number().optional(),
        opacity: z.number().optional(),
        rotate: z.number().optional(),
        fullPage: z.boolean().optional(),
      }),
    ]).optional(),
    plot: z.object({
      trigger: z.enum(['hover', 'click']).optional(),
      effect: z.enum(['mask', 'blur']).optional(),
    }).optional(),
    sticky: z.union([z.boolean(), z.number()]).optional(),
    cover: z.string().optional(),
    banner: z.string().optional(),
    coverStyle: z.object({
      layout: z.enum(['left', 'right', 'odd-left', 'odd-right', 'top']).optional(),
      ratio: z.union([z.number(), z.string()]).optional(),
      width: z.number().optional(),
      compact: z.boolean().optional(),
    }).optional(),
    friends: z.boolean().optional(),
    contentPosition: z.enum(['before', 'after']).optional(),
    cols: z.number().optional(),
    list: z.array(friendItemSchema).optional(),
    groups: z.array(z.object({
      title: z.string().optional(),
      desc: z.string().optional(),
      list: z.array(friendItemSchema).optional(),
    })).optional(),
  }),
})

export const collections = { content }
